/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio;

import javax.swing.JOptionPane;

/**
 *
 * @author ANDRES
 */
public class VistaEquipos extends javax.swing.JDialog {
    Equipos local = new Equipos();
    Equipos visita = new Equipos();

    /**
     * Creates new form VistaEquipos
     */
    public VistaEquipos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonReinicio = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelLocal = new javax.swing.JLabel();
        labelVisita = new javax.swing.JLabel();
        botonSimpleLocal = new javax.swing.JButton();
        botonDobleLocal = new javax.swing.JButton();
        botonTripleLocal = new javax.swing.JButton();
        botonMenosunoLocal = new javax.swing.JButton();
        botonSimpleVisita = new javax.swing.JButton();
        botonDobleVisita = new javax.swing.JButton();
        botonTripleVisita = new javax.swing.JButton();
        botonMenosUnoVisita = new javax.swing.JButton();
        botonresultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Liga Nacional de Basquet");

        botonReinicio.setText("Reiniciar Tablero");
        botonReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReinicioActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("LOCAL");

        jLabel3.setText("VISITA");

        labelLocal.setText("0");

        labelVisita.setText("0");

        botonSimpleLocal.setText("Simple");
        botonSimpleLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimpleLocalActionPerformed(evt);
            }
        });

        botonDobleLocal.setText("Doble");
        botonDobleLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDobleLocalActionPerformed(evt);
            }
        });

        botonTripleLocal.setText("Triple");
        botonTripleLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTripleLocalActionPerformed(evt);
            }
        });

        botonMenosunoLocal.setText("-1");
        botonMenosunoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenosunoLocalActionPerformed(evt);
            }
        });

        botonSimpleVisita.setText("Simple");
        botonSimpleVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimpleVisitaActionPerformed(evt);
            }
        });

        botonDobleVisita.setText("Doble");
        botonDobleVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDobleVisitaActionPerformed(evt);
            }
        });

        botonTripleVisita.setText("Triple");
        botonTripleVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTripleVisitaActionPerformed(evt);
            }
        });

        botonMenosUnoVisita.setText("-1");
        botonMenosUnoVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenosUnoVisitaActionPerformed(evt);
            }
        });

        botonresultado.setText("Resultado");
        botonresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonresultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonReinicio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelLocal)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(botonSalir))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDobleLocal)
                    .addComponent(botonSimpleLocal)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonMenosunoLocal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonTripleLocal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addComponent(botonresultado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSimpleVisita)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelVisita)
                        .addComponent(jLabel3))
                    .addComponent(botonDobleVisita)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botonMenosUnoVisita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonTripleVisita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonresultado))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir)
                    .addComponent(botonReinicio))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocal)
                    .addComponent(labelVisita))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSimpleLocal)
                    .addComponent(botonSimpleVisita))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonDobleLocal)
                    .addComponent(botonDobleVisita))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonTripleLocal)
                    .addComponent(botonTripleVisita))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMenosunoLocal)
                    .addComponent(botonMenosUnoVisita))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
       dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonSimpleLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimpleLocalActionPerformed
        labelLocal.setText(String.valueOf(local.contadorsimple()));
    }//GEN-LAST:event_botonSimpleLocalActionPerformed

    private void botonDobleLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDobleLocalActionPerformed
        labelLocal.setText(String.valueOf(local.contadordoble()));
    }//GEN-LAST:event_botonDobleLocalActionPerformed

    private void botonReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReinicioActionPerformed
        actualizar();
    }//GEN-LAST:event_botonReinicioActionPerformed

    private void botonTripleLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTripleLocalActionPerformed
        labelLocal.setText(String.valueOf(local.contadortriple()));
    }//GEN-LAST:event_botonTripleLocalActionPerformed

    private void botonMenosunoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenosunoLocalActionPerformed
        labelLocal.setText(String.valueOf(local.decrementar()));
    }//GEN-LAST:event_botonMenosunoLocalActionPerformed

    private void botonSimpleVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimpleVisitaActionPerformed
        labelVisita.setText(String.valueOf(visita.contadorsimple()));
    }//GEN-LAST:event_botonSimpleVisitaActionPerformed

    private void botonDobleVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDobleVisitaActionPerformed
        labelVisita.setText(String.valueOf(visita.contadordoble()));
    }//GEN-LAST:event_botonDobleVisitaActionPerformed

    private void botonTripleVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTripleVisitaActionPerformed
       labelVisita.setText(String.valueOf(visita.contadortriple()));
    }//GEN-LAST:event_botonTripleVisitaActionPerformed

    private void botonMenosUnoVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenosUnoVisitaActionPerformed
        labelVisita.setText(String.valueOf(visita.decrementar()));
    }//GEN-LAST:event_botonMenosUnoVisitaActionPerformed

    private void botonresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonresultadoActionPerformed
        int numlocal = Integer.parseInt(labelLocal.getText());
        int numvisitante = Integer.parseInt(labelVisita.getText());
        
        if (numlocal > numvisitante) 
        {
            JOptionPane.showMessageDialog(null, "EL GANADOR ES EL EQUIPO LOCAL CON = " + numlocal + " PUNTOS");
            
        }
        
        if (numvisitante > numlocal ) 
        {
            JOptionPane.showMessageDialog(null, "EL GANADOR ES EL EQUIPO VISITANTE CON =  " + numvisitante + " PUNTOS");
            
        }
        else
        {
            if (numlocal == numvisitante) 
            {
                JOptionPane.showMessageDialog(null, "AMBOS EQUIPOS EMPATARON ");
                
            }
        
        }
    }//GEN-LAST:event_botonresultadoActionPerformed

    public void actualizar()
    {
        labelLocal.setText("-");
        labelVisita.setText("-");
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaEquipos dialog = new VistaEquipos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDobleLocal;
    private javax.swing.JButton botonDobleVisita;
    private javax.swing.JButton botonMenosUnoVisita;
    private javax.swing.JButton botonMenosunoLocal;
    private javax.swing.JButton botonReinicio;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSimpleLocal;
    private javax.swing.JButton botonSimpleVisita;
    private javax.swing.JButton botonTripleLocal;
    private javax.swing.JButton botonTripleVisita;
    private javax.swing.JButton botonresultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelLocal;
    private javax.swing.JLabel labelVisita;
    // End of variables declaration//GEN-END:variables
}
